[eas-cli] Improve reliability of update asset presigned upload requests
expo/eas-cli pull request #1278
Opened 2022-08-16 00:10 UTC by wschurman

# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

Google cloud storage says to retry with exponential backoff when the uploads throw an error: https://cloud.google.com/storage/docs/request-rate

I was seeing `ECONNRESET` errors locally when uploading huge numbers of assets, and this seemed to fix it.

# How

Add `promise-retry` with 3 retries with exponential backoff.

# Test Plan

With app with 3k assets, run:
```
~/expo/eas-cli/packages/eas-cli/bin/run update --branch preview --message "Updating the app"
```

(pointed at my local EAS server with the 700 limit disabled temporarily)

2022-08-16 02:37 UTC, ide requested changes

2022-08-16 02:37 UTC, ide commented on packages/eas-cli/src/uploads.ts
> +        return retry(new Error(`Presigned post responded with a ${response.status}`));
```suggestion
        return retry(new Error(`Presigned upload responded with a ${response.status} status`));
```

2022-08-16 02:37 UTC, ide commented on packages/eas-cli/src/uploads.ts
> +    }
May want to link to https://cloud.google.com/storage/docs/retry-strategy#node.js saying the parameters were chosen by matching GCS's defaults

2022-08-16 02:39 UTC, ide commented on packages/eas-cli/src/uploads.ts
> +      if (!response.ok) {
(Comment was lost) Requesting changes to look at the response status and retry only on 408, 429, and 5xx errors. I don't think it's useful to retry a 401 for example.

2022-08-16 02:40 UTC, ide commented on packages/eas-cli/src/uploads.ts
> +          handleProgressEvent
Behavior to test: what happens on a retry when the progress potentially goes backwards (a retry will start over at 0%)?

2022-08-16 07:56 UTC, dsokal reviewed
LGTM

2022-08-16 18:03 UTC, wschurman commented
/changelog-entry new-feature Improve reliability of update asset presigned upload requests

2022-08-16 23:57 UTC, ide approved these changes

2022-08-16 23:57 UTC, ide commented on packages/eas-cli/src/uploads.ts
> +async function uploadWithPresignedPostAsync(
Might be overoptimizing for code deduplication but one clean way to reduce duplicate code between this method and uploadWithPresignedPostWithProgressAsync would be to change this method to `createPresignedPostRequest: Request`, which returns an object that can be passed to fetch().

uploadWithPresignedPostWithProgressAsync can get the FormData object from the Request to add listeners to it before passing the Request to fetch().

2022-08-17 08:05 UTC, dsokal commented on packages/eas-cli/src/uploads.ts
> +        Math.floor(response.status / 100) === 5 // 5xx errors
Even though it's probably more readable, I'd prefer to avoid using Yoda notation :D

2022-08-17 17:59 UTC, merged

2022-08-17 18:28 UTC, wschurman commented on CHANGELOG.md
> +>>>>>>> 1ff5f69a (update CHANGELOG.md)
ugh lol