use version check for disabling global CLI
expo/eas-cli pull request #1474
Opened 2022-10-24 19:07 UTC by EvanBacon

# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

- revert 51db45a8

# Test Plan

- Added tests

2022-10-24 19:08 UTC, EvanBacon commented
/changelog-entry new-feature use local CLI for `expo export` in SDK +46

2022-10-24 20:51 UTC, brentvatne approved these changes

2022-10-25 08:09 UTC, dsokal requested changes
Requesting changes because of the `getConfig` comment.

2022-10-25 08:09 UTC, dsokal commented on packages/eas-cli/src/utils/expoCli.ts
> +    const { sdkVersion } = getConfig(projectDir).exp;
Don't call `getConfig` explicitly. This should be passed from the command's context. Talk with @wschurman if you need details :)

2022-10-25 08:09 UTC, dsokal commented on packages/eas-cli/src/utils/expodash/memoize.ts
> +  }) as any;
🤔 
```suggestion
  }) as T;
```

2022-10-26 18:44 UTC, EvanBacon commented on packages/eas-cli/src/utils/expoCli.ts
> +  }
yes

2022-10-27 08:41 UTC, dsokal requested changes

2022-10-27 08:41 UTC, dsokal commented on CHANGELOG.md
> +- Use local CLI for `expo export` in SDK +46. ([#1474](https://github.com/expo/eas-cli/pull/1474) by [@EvanBacon](https://github.com/EvanBacon))
Rebase and move to the unreleased section.

2022-10-27 08:41 UTC, dsokal commented on packages/eas-cli/src/utils/expoCli.ts
> +    const { sdkVersion } = getExpoConfig(projectDir);
My comment is still not addressed.
The ExpoConfig object should be passed from the top-level code (publish/index.ts):

```diff
diff --git a/packages/eas-cli/src/commands/update/index.ts b/packages/eas-cli/src/commands/update/index.ts
index abdde689..9ae47247 100644
--- a/packages/eas-cli/src/commands/update/index.ts
+++ b/packages/eas-cli/src/commands/update/index.ts
@@ -391,7 +391,7 @@ export default class UpdatePublish extends EasCommand {
       if (!skipBundler) {
         const bundleSpinner = ora().start('Building bundle...');
         try {
-          await buildBundlesAsync({ projectDir, inputDir });
+          await buildBundlesAsync({ exp, projectDir, inputDir });
           bundleSpinner.succeed('Built bundle!');
         } catch (e) {
           bundleSpinner.fail('Failed to build bundle!');
diff --git a/packages/eas-cli/src/project/publish.ts b/packages/eas-cli/src/project/publish.ts
index 7726e3b0..a12273b2 100644
--- a/packages/eas-cli/src/project/publish.ts
+++ b/packages/eas-cli/src/project/publish.ts
@@ -146,9 +146,11 @@ export async function buildUnsortedUpdateInfoGroupAsync(
 }
 
 export async function buildBundlesAsync({
+  exp,
   projectDir,
   inputDir,
 }: {
+  exp: ExpoConfig;
   projectDir: string;
   inputDir: string;
 }): Promise<void> {
@@ -157,7 +159,7 @@ export async function buildBundlesAsync({
     throw new Error('Could not locate package.json');
   }
 
-  if (shouldUseVersionedExpoCLI(projectDir)) {
+  if (shouldUseVersionedExpoCLI(projectDir, exp)) {
     await expoCommandAsync(projectDir, ['export', '--output-dir', inputDir, '--dump-sourcemap']);
   } else {
     // Legacy global Expo CLI
diff --git a/packages/eas-cli/src/utils/expoCli.ts b/packages/eas-cli/src/utils/expoCli.ts
index 4a2342eb..dc7a3912 100644
--- a/packages/eas-cli/src/utils/expoCli.ts
+++ b/packages/eas-cli/src/utils/expoCli.ts
@@ -1,3 +1,4 @@
+import { ExpoConfig } from '@expo/config-types';
 import spawnAsync from '@expo/spawn-async';
 import chalk from 'chalk';
 import { boolish } from 'getenv';
@@ -5,7 +6,6 @@ import resolveFrom from 'resolve-from';
 import semver from 'semver';
 
 import Log from '../log';
-import { getExpoConfig } from '../project/expoConfig';
 import { memoize } from './expodash/memoize';
 
 // Aggressively returns `true` (UNVERSIONED, invalid SDK version format) to push users towards the versioned CLI.
@@ -24,7 +24,7 @@ function gteSdkVersion(fromSdkVersion: string, sdkVersion: string): boolean {
 /**
  * @returns `true` if the project is SDK +46, has `@expo/cli`, and `EXPO_USE_LOCAL_CLI` is not set to a _false_ value.
  */
-export function shouldUseVersionedExpoCLIExpensive(projectDir: string): boolean {
+export function shouldUseVersionedExpoCLIExpensive(projectDir: string, exp: ExpoConfig): boolean {
   // Users can disable local CLI settings EXPO_USE_LOCAL_CLI=false
   // https://github.com/expo/expo/blob/69eddda7bb1dbfab44258f468cf7f22984c1e44e/packages/expo/bin/cli.js#L10
   // Run the environment variable check first as it's the cheapest.
@@ -36,7 +36,7 @@ export function shouldUseVersionedExpoCLIExpensive(projectDir: string): boolean
   try {
     // NOTE(EvanBacon): The CLI package could be available through a monorepo
     // we need to ensure the project is specifically using a known supported Expo SDK version.
-    const { sdkVersion } = getExpoConfig(projectDir);
+    const { sdkVersion } = exp;
 
     if (
       // If the version isn't defined then skip the check.
```

2022-11-03 02:22 UTC, merged

2022-11-03 08:13 UTC, dsokal commented on CHANGELOG.md
> +- Use local CLI for `expo export` in SDK +46. ([#1474](https://github.com/expo/eas-cli/pull/1474) by [@EvanBacon](https://github.com/EvanBacon))
This is not addressed. You haven't rebased your branch. I'll fix it in main.