[eas-cli] Adds channels to build profiles on eas update:configure
expo/eas-cli pull request #1570
Opened 2022-12-07 18:55 UTC by jonsamp

# Checklist

- [x] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

To make EAS Update easier to set up, we are adding `channel` properties to build profiles when running `eas update:configure`.

The logic is:
- If eas.json is present:
  - if there is not pre-existing channel or release channel, set a channel named after the profile name
  - else do nothing (leave as is)
- else warn that the developer may need to run `eas build:configure`, then re-run `eas update:configure` to set everything up.

In addition, I updated the "Next steps" text, so there's actionable items after running `eas update:configure`.

<img width="861" alt="Screenshot 2022-12-07 at 12 47 10 PM" src="https://user-images.githubusercontent.com/6455018/206269931-8b89ea20-5e3e-4c3b-863c-d6ad077677ed.png">

# Test Plan

Run `easd update:configure` in a project. Check:
- that projects with channels in build profiles are not overwritten
- that projects with release channels in build profiles are not overwritten
- that projects get a channel when none is specified after running `eas update:configure`
- that if **eas.json** is not present, you see a readable error message

2022-12-07 18:56 UTC, jonsamp commented
/changelog-entry new-feature add channel configurations to **eas.json** during `eas update:configure`

2022-12-08 08:46 UTC, dsokal requested changes
Requesting changes mostly because this doesn't work with eas.json with JSON5.

2022-12-08 08:46 UTC, dsokal commented on packages/eas-cli/src/commands/update/configure.ts
> +    Log.log(`3. Publish an update. Example: ${chalk.green('`eas update --channel production`')}.`);
This is the convention in this repo:
```suggestion
    Log.log(`1. Create a new build. Example: ${chalk.bold('eas build --profile production')}.`);
    Log.log('2. Make changes in your project.');
    Log.log(`3. Publish an update. Example: ${chalk.bold('eas update --channel production')}.`);
```

See 
<img width="583" alt="Screenshot 2022-12-08 at 09 36 06" src="https://user-images.githubusercontent.com/5256730/206398485-98545152-71a0-4b63-be48-f497abd6c0c1.png">

2022-12-08 08:46 UTC, dsokal commented on packages/eas-cli/src/commands/update/configure.ts
> +      )}.`
```suggestion
      `1. Publish an update to a branch. Example: ${chalk.bold(
        'eas update --branch new-feature'
      )}.`
```

2022-12-08 08:46 UTC, dsokal commented on packages/eas-cli/src/update/configure.ts
> +async function ensureEASUpdateIsConfiguredInEasConfigAsync({
```suggestion
async function ensureEASUpdateIsConfiguredInEasJsonAsync({
```

2022-12-08 08:46 UTC, dsokal commented on packages/eas-cli/src/update/configure.ts
> +async function ensureEASUpdateIsConfiguredInEasConfigAsync({
And rename all variables in this function from `easConfig` to `easJson`. We shouldn't use more than one name for the same thing. It's really confusing for new people reading the code.

2022-12-08 08:46 UTC, dsokal commented on packages/eas-cli/src/update/configure.ts
> +}): Promise<void> {
IMO pass just `projectDir` to the function (not an object with `projectDir`). There's no need to make this future-proof as this is really easy to change.

2022-12-08 08:46 UTC, dsokal commented on packages/eas-cli/src/update/configure.ts
> +  }
eas.json supports JSON5. This doesn't work for JSON5 files. 
You should use https://github.com/expo/eas-cli/blob/main/packages/eas-json/src/accessor.ts#L91
Example of usage: https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts#L131

2022-12-08 08:46 UTC, dsokal commented on packages/eas-cli/src/update/configure.ts
> +  if (await fs.pathExists(easConfigPath)) {
Prefer returning early from functions:
```suggestion
  if (!await fs.pathExists(easConfigPath)) {
    Log.warn(...);
    return;
```

2022-12-08 08:46 UTC, dsokal commented on packages/eas-cli/src/update/configure.ts
> +      `EAS Build is not configured. If you'd like to use EAS Build with EAS Update, run \`eas build:configure\`, then re-run \`eas update:configure\` to configure ${chalk.bold(
You're printing commands in logs inconsistently in this PR. Elsewhere you used `chalk.green(...)`. See my other comment.

2022-12-08 19:17 UTC, byCedric approved these changes
Besides the JSON5 part, seems good 👍

2022-12-09 09:30 UTC, dsokal approved these changes

2022-12-09 09:30 UTC, dsokal commented on packages/eas-cli/src/update/configure.ts
> +      `EAS Build is not configured. If you'd like to use EAS Build with EAS Update, run \`eas build:configure\`, then re-run ${chalk.bold(
```suggestion
      `EAS Build is not configured. If you'd like to use EAS Build with EAS Update, run ${chalk.bold('eas build:configure')}, then re-run ${chalk.bold(
```

2022-12-09 09:40 UTC, wkozyra95 approved these changes

2022-12-12 16:59 UTC, merged