[ENG-11076][eas-cli] prompt user to map channel on update if unmapped
expo/eas-cli pull request #2185
Opened 2024-01-18 03:53 UTC by quinlanj

# Why
When an update is created with the `channel` flag, it will error if the channel is not mapped to a branch. 

```
> eas update --channel main
Channel has no branches associated with it. Run 'eas channel:edit' to map a branch
```

This PR allows the user to select the branch to map in this case:
```
>  eas-dev update --channel blah
Channel has no branches associated with it.
✔ Which branch would you like blah to point at? › gh/quinlanj/3/orig
```

# Test Plan

- [ ] amended test to expect new behaviour

2024-01-18 04:04 UTC, quinlanj commented
/changelog-entry chore  prompt user to map channel on update if unmapped

2024-01-18 10:15 UTC, szdziedzic approved these changes

2024-01-18 18:49 UTC, wschurman commented
It feels awkward to me that we allow creating an update with just a channel flag since updates are associated with branches instead of channels. I assume the channel flag was added as a convenience flag for singly-mapped channel-branch combinations? 

PR that added it makes it seem like this behavior might have been intentional: https://github.com/expo/eas-cli/pull/1567 
cc @jonsamp

2024-01-18 18:53 UTC, wschurman commented
I guess my other worry is that this might be too heavy of an operation for people to comprehend what is being done. By pointing an existing channel at an existing branch, any other/existing builds with that channel will now receive compatible updates on that branch. I worry that people running a simple `eas update` command may not comprehend the potential magnitude of such an operation and may just answer "yes" out of habit, which could have unintended consequences in production.

2024-01-19 17:23 UTC, wschurman requested changes
Requesting changes for now to put it back in your queue to assess.

2024-01-19 18:33 UTC, quinlanj commented
@wschurman you raise a really good point in https://github.com/expo/eas-cli/pull/2185#issuecomment-1899035520 . People will have to select a branch to map to a channel (they don't reply `y`), but I agree someone could just be pressing the Return key out of habit, not expecting that some variant of `eas update` would change the mapping of their channel. 

Closing this PR to retain the original behaviour.

2024-01-19 18:33 UTC, closed without merging