[eas-cli] use generated graphql types
expo/eas-cli pull request #262
Opened 2021-03-02 22:55 UTC by jkhales

# Why

Using generated graphql code types for commands leaves less room for error.

# How

Used pregenerated graphql types where appropriate.

# Test Plan

tested commands still work in a test project.

2021-03-02 23:22 UTC, jkhales commented on packages/eas-cli/src/commands/branch/list.ts
> -    }
replaced this custom error handling with `withErrorHandlingAsync` above.

2021-03-03 14:23 UTC, fson requested changes
Thanks, this makes the types much more useful.

2021-03-03 14:23 UTC, fson commented on packages/eas-cli/src/commands/branch/view.ts
> +      .mutation<ViewBranchQuery, ViewBranchQueryVariables>(
```suggestion
      .query<ViewBranchQuery, ViewBranchQueryVariables>(
```

2021-03-03 14:23 UTC, fson commented on packages/eas-cli/src/commands/build/cancel.ts
> +      .mutation<CancelBuildMutation>(
```suggestion
      .mutation<CancelBuildMutation, CancelBuildMutationVariables>(
```

2021-03-03 14:23 UTC, fson commented on packages/eas-cli/src/commands/build/cancel.ts
> +import { AppPlatform, Build, BuildStatus, CancelBuildMutation } from '../../graphql/generated';
```suggestion
import { AppPlatform, Build, BuildStatus, CancelBuildMutation, CancelBuildMutationVariables } from '../../graphql/generated';
```

2021-03-03 14:40 UTC, fson approved these changes

2021-03-03 14:53 UTC, merged