[eas-cli] create fingerprint on each update
expo/eas-cli pull request #2687
Opened 2024-11-13 03:56 UTC by quinlanj

# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

2024-11-13 03:56 UTC, quinlanj commented
* **#2687** <a href="https://app.graphite.dev/github/pr/expo/eas-cli/2687?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @quinlanj and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-15 17:40 UTC, Kudo approved these changes

2024-11-15 17:40 UTC, Kudo commented on packages/eas-cli/src/project/publish.ts
> +export async function maybeCalculateFingerprintForRuntimeVersionInfoObjectsWithoutExpoUpdatesAsync({
nit: the logic of this function is kind of complicated. would be good to split as smaller functions and add some unit test.
but fine if that requires too much effort.

2024-11-18 22:46 UTC, wschurman requested changes
Think we also need to add this to republish. Probably just pull in the fingerprint from the previously-published update assuming we are sure it won't change between publish and republish (don't think we have another option since we can't re-calculate the fingerprint on republish since republish can't use any info from the current project state, code signing suffers from this fwiw)

2024-11-18 22:47 UTC, wschurman commented
(if you want to do republish in a follow-up, request re-review on this one. this looks good otherwise)

2024-11-18 22:49 UTC, wschurman commented
Also, should roll-back-to-embedded updates have this as well? (every command that calls `publishUpdateGroupAsync` should have it I think?)

2024-11-20 02:40 UTC, quinlanj commented
@wschurman here is the PR for republishing (made separate because of extra dependencies on www changes): https://github.com/expo/eas-cli/pull/2708

I dont think we need to pass on fingerprint info for rollback to embedded. A 'rollback to embedded' directive would always be compatible with whatever build that is targeted. Also, it would technically have the fingerprint of the receiving build (ideally all builds of the same runtime have the same fingerprint, but that's not necessarily the case)

2024-11-20 04:10 UTC, wschurman approved these changes
> I dont think we need to pass on fingerprint info for rollback to embedded.

My guess is that it might be simpler product-wise to include them since they are just normal UpdateEntities (as are rollouts and republishes). Otherwise we'd need to special case the UI to explain why they don't have them for those updates?

> A 'rollback to embedded' directive would always be compatible with whatever build that is targeted. Also, it would technically have the fingerprint of the receiving build (ideally all builds of the same runtime have the same fingerprint, but that's not necessarily the case)

I believe they're only compatible with builds with the same code signing key (and therefore theoretically runtime version as we advise people to change when they do a key change). I think since the code signing configuration is part of the fingerprint we should probably attach the fingerprint to directives.

2024-11-20 21:43 UTC, merged