Move environment from metadata to job object
expo/eas-cli pull request #2777
Opened 2024-12-18 12:27 UTC by khamilowicz

# Why

[ENG-14307: move environment to job object from metadata](https://linear.app/expo/issue/ENG-14307/move-environment-to-job-object-from-metadata)

`Environment` should be considering  a first class citizen in job object instead of being stored in the metadata.

# How

* Pass `environment` in `job` object
* remove `environment` from `metadata`.

# Test Plan

1. Start a build specifying `environment` in `eas.json`.
2. Build should use the specified environment (check on website in `Build details`)

2025-01-27 15:24 UTC, sjchmiela requested changes

2025-01-27 16:19 UTC, khamilowicz commented on packages/eas-cli/src/build/utils/environment.ts
> +  return null;
`eas-json` already takes care of this: 

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/KfcKByW8uA9rvjzBy0RA/e098b13d-8b15-4a61-8673-68ff2bda5df8.png)

2025-01-29 15:42 UTC, khamilowicz commented on packages/eas-cli/src/build/utils/environment.ts
> +};
What do you think about `type Environment = NonNullable<BuildProfile['environment']>`?
As for adding new environment - I have a feeling that if we ever change environments, it will be for a user-defined value.

2025-01-29 17:07 UTC, szdziedzic commented on packages/eas-cli/src/build/utils/environment.ts
> +};
Cool we can do `NonNullable<BuildProfile['environment']>` 👍 I just wanted to alter this code in a way it warns us if any changes are necessary based on this type in the future 😄

2025-01-29 17:08 UTC, szdziedzic approved these changes
looks good

2025-01-29 20:54 UTC, sjchmiela approved these changes

2025-01-30 09:31 UTC, merged