[eas-cli] Enhance `eas env:exec` command by enabling shell execution for commands
expo/eas-cli pull request #2788
Opened 2024-12-21 23:32 UTC by tharakadesilva

# Why

This change initiated from the comments of https://github.com/expo/expo-github-action/pull/316.

The [first issue](https://github.com/expo/expo-github-action/pull/316#issuecomment-2543879065) we faced was that the commands passed to `env:exec` was not found when ran through a Github action:

```
[stderr] bash: line 1: npx expo config --json --type public: command not found
❌ "npx expo config --json --type public" failed
bash -c "npx expo config --json --type public" exited with non-zero code: 127
    Error: env:exec command failed.
```

Once that was fixed, [the second issue](https://github.com/expo/expo-github-action/pull/316#issuecomment-2552366932) was that it was failing when ran local terminals even though it started to pass in CI:

```
$ neas env:exec preview "npx expo config --json --type public"
No environment variables with visibility "Plain text" and "Sensitive" found for the "preview" environment on EAS servers.

Running command: npx expo config --json --type public
[stdout] Entering npm script environment at location:
[stdout] /Users/wschurman/temp/pkfsapjfasafjpfajaf
[stdout] Type 'exit' or ^D when finished
```

# How

For the first issue, we followed [this answer](https://stackoverflow.com/a/44987029) and added `shell: true` to spawn.

> While calling spawn itself, there is no npm command under spawn. Thus you got that error message. Instead of using spawn itself, while adding shell: true, spawn will use shell of your system to run that command. Since your system has npm, it works.

For the second issue, we wrapped the command in quotes and escaped them in case the command supplied by the user had quotes.

# Test Plan

* Tested the command works on Github CI
* Ran the following commands locally

```
expo/eas-cli/packages/eas-cli/bin/run env:exec preview "npx expo config --json --type public"
Environment variables with visibility "Plain text" and "Sensitive" loaded from the "preview" environment on EAS: BUILD_VAR, EXPO_PUBLIC_UPDATE_VAR.

Running command: npx expo config --json --type public
[stdout] {"name":"Your Projects name" ... }
```

```
expo/eas-cli/packages/eas-cli/bin/run env:exec preview "echo 'hello
world'"             
Environment variables with visibility "Plain text" and "Sensitive" loaded from the "preview" environment on EAS: BUILD_VAR, EXPO_PUBLIC_UPDATE_VAR.

Running command: echo 'hello
world'
[stdout] hello
[stdout] world
```

2024-12-21 23:34 UTC, tharakadesilva commented
/changelog-entry bug-fix [eas-cli] Enhance eas env:exec command by enabling shell execution for commands

2025-01-08 10:04 UTC, szdziedzic commented on packages/eas-cli/src/commands/env/exec.ts
> +      shell: true,
I'm not sure if I fully understand why `bash -c` doesn't work on CI but it does on my local machine 🤔 Do you fully get it? Do you use Windows on CI by any chance?

2025-01-08 22:05 UTC, tharakadesilva commented on packages/eas-cli/src/commands/env/exec.ts
> +      shell: true,
> Do you fully get it?

Hey Szymon, unfortunately, no... I am baffled too...

> Do you use Windows on CI by any chance?

Nope, I use Github actions with `runs-on: ubuntu-latest`.

---

It's totally weird, but even the quote issue seems to be happening only on CI...

2025-01-09 20:45 UTC, wschurman requested changes
LGTM. Only change is to rebase and apply the same fix to the new `runCommandNonInteractiveWithEnvVarsAsync`. Otherwise, this looks like it might be what's required to fix the issues. Definitely hard to understand the "why" these are the case in CI only, but really we need to do whatever is required to get this command (`eas env:exec --non-interactive`) to be a pure passthrough. 

Relatedly, I almost wonder if it makes more sense to recommend using `eas env:pull` and then source .env in CI? cc @szdziedzic

2025-01-10 10:27 UTC, szdziedzic commented
>Relatedly, I almost wonder if it makes more sense to recommend using eas env:pull and then source .env in CI? cc

I believe it should also work 🤔 At least for `generate-fingerprint`

2025-01-10 23:59 UTC, tharakadesilva commented
Closing this in lieu of Will's MR here: https://github.com/expo/eas-cli/pull/2811

2025-01-10 23:59 UTC, closed without merging