[eas-cli] add channel:rollout start command
expo/eas-cli pull request #290
Opened 2021-03-24 20:21 UTC by jkhales

# Why

Create a command to start a rollout on a channel.

# How

* Recycled graphQL calls from other commands.
* converted the existing branchMapping to a rollout.

# Test Plan

Manually started a rollout:

<img width="1317" alt="Screen Shot 2021-03-24 at 1 19 09 PM" src="https://user-images.githubusercontent.com/1220444/112377926-87277500-8ca3-11eb-8bce-f3d46b944df3.png">

2021-03-25 20:32 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +      // this will likely be removed as more commands fill out
delete.

2021-03-25 20:33 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +      throw new Error('This CLI cannot handle branch mappings with more than 2 branches.');
```suggestion
      throw new Error('"channel:rollout" cannot handle branch mappings with more than 2 branches.');
```

2021-03-25 20:36 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +    if (isRollout && branchName && !endFlag) {
add comment that the user is likely trying to start a rollout here since they have supplied a branch name and no end flag.

2021-03-25 20:43 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +    } else if (!endFlag) {
add comment that this is for managing.

2021-03-25 20:44 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +      }
delet in favor of: https://github.com/expo/eas-cli/pull/290/files#diff-5e715a56413f58e4e51aad67353e66469536e961c39884dd972b572a3d847f2dR206

2021-03-25 20:50 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +      }
pull this out into seperate function and use in the `--end` code block as well.

2021-03-25 20:50 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +      throw new Error('');
Add message.

2021-03-25 20:51 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +    let newChannelInfo, logMessage;
Add comment explaining this big if/else block

2021-03-26 12:45 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +async function getPercentAsync({
```suggestion
async function getRolloutPercentAsync({
```

2021-03-26 12:45 UTC, jkhales commented on packages/eas-cli/src/commands/channel/rollout.ts
> +       */
🤔

2021-03-29 15:37 UTC, jonsamp commented
For the `--end` flag, do we have to specify the branch? I assume not, since channel `main` can only ever have one rollout alive at once.

As a UX thing, can we change text like this:

```
90% of users will be directed to **test**, 10% to **main**.
```

to:

```
90% of users will be directed to the **test** branch; 10% to the **main** branch.
```

Since channels and branches will often have the same name, I think it's important we try to say "branch" and "channel".

2021-03-29 15:47 UTC, jonsamp approved these changes
This code looks reasonable to me. I read through it all and it makes sense. Happy to do testing if you want to feel more confident about shipping this.

2021-03-29 15:47 UTC, jonsamp commented on packages/eas-cli/src/commands/channel/rollout.ts
> +                `The branch "${branchName}"specified by --branch must be one of the branches involved in the rollout: "${newBranch.name}" or "${oldBranch.name}".`
```suggestion
                `The branch "${branchName}" specified by --branch must be one of the branches involved in the rollout: "${newBranch.name}" or "${oldBranch.name}".`
```

2021-03-30 12:41 UTC, fson requested changes

2021-03-30 15:45 UTC, jkhales commented on packages/eas-cli/src/commands/channel/view.ts
> +      if (rolloutPercent === undefined) {
good idea

2021-03-30 19:47 UTC, fson approved these changes

2021-03-30 20:43 UTC, merged