use custom ora instance
expo/eas-cli pull request #575
Opened 2021-08-24 20:04 UTC by EvanBacon

# Checklist

- [ ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary.
- [ ] I've tagged the changelog entry with `[EAS BUILD API]` if it's a part of a breaking change to EAS Build API (only possible when updating `@expo/eas-build-job` package).

# Why

Prevent debug logs from breaking spinners

## Before

<img width="1073" alt="Screen Shot 2021-08-24 at 2 00 12 PM" src="https://user-images.githubusercontent.com/9664363/130682209-ef7f839f-22c0-4f48-8e61-432511a451ed.png">

## After

<img width="1089" alt="Screen Shot 2021-08-24 at 1 59 59 PM" src="https://user-images.githubusercontent.com/9664363/130682228-f888020f-8db0-4dc8-ae7b-fcd95d70a5f8.png">

# How

override logs and pause ora before logging to the console, also disable ora when EXPO_DEBUG is enabled.

# Test Plan

- `EXPO_DEBUG=1 eas build` -- static spinners
- `EXPO_APP_STORE_DEBUG=1 eas build` -- no broken logs

2021-08-25 08:50 UTC, dsokal requested changes

2021-08-25 08:50 UTC, dsokal commented on packages/eas-cli/src/ora.ts
> +  const ora = oraReal({
You're shadowing the function, pick a different name for the variable.

2021-08-25 08:50 UTC, dsokal commented on packages/eas-cli/src/ora.ts
> +  const inputOptions = typeof options === 'string' ? { text: options } : options || {};
- Add parentheses around `options || {}`. It's helpful for readers so they don't need to think about which operator has higher precedence. 
- Prefer `?? {}` over `|| {}`.

2021-08-25 08:50 UTC, dsokal commented on packages/eas-cli/src/ora.ts
> +    ora!.start();
```suggestion
    ora.start();
```
I checked out your branch locally and verified that `!` is not necessary.

2021-08-25 08:50 UTC, dsokal commented on packages/eas-cli/src/ora.ts
> +    return ora!;
```suggestion
    return ora;
```
Same here

2021-08-25 08:50 UTC, dsokal commented on packages/eas-cli/src/ora.ts
> +    return ora!;
```suggestion
    return ora;
```
And here.

2021-08-25 08:50 UTC, dsokal commented on packages/eas-cli/src/ora.ts
> +  console.error = (...args: any) => logWrap(errorReal, args);
This block should go to `ora.start`. You can create an ora instance first and start it later.

2021-08-25 08:50 UTC, dsokal commented on packages/eas-cli/src/ora.ts
> +  const origStopAndPersist = ora.stopAndPersist.bind(ora);
Use consistent naming. E.g. `oraStop` + `oraStopAndPersist` or `origStop` + `orig StopAndPersist`.

2021-09-07 14:23 UTC, dsokal commented
@EvanBacon There's one more comment before we can merge it. Let me know if you want me to take over this PR.

2021-09-20 13:42 UTC, dsokal approved these changes

2021-09-20 14:12 UTC, wkozyra95 approved these changes

2021-09-20 14:36 UTC, merged