[eas-cli] support staging and local Update URLs
expo/eas-cli pull request #849
Opened 2021-12-14 21:51 UTC by jkhales

# Checklist

- [x] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary. You can comment this pull request with `/changelog-entry [breaking-change|new-feature|bug-fix|chore] [message]` and CHANGELOG.md will be updated automatically.

# Why

To make development easier, support staging and local update URLs

2021-12-15 09:37 UTC, dsokal requested changes

2021-12-15 09:37 UTC, dsokal commented on packages/eas-cli/src/commands/update/configure.ts
> +  }
Move this logic to https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/api.ts

2021-12-15 16:25 UTC, wkozyra95 approved these changes

2021-12-15 16:25 UTC, wkozyra95 commented on packages/eas-cli/src/api.ts
> +export async function getEASUpdateURLAsync(projectId: string): Promise<string> {
This function does not need to be async

2021-12-16 08:43 UTC, dsokal approved these changes

2021-12-16 15:14 UTC, merged